### ISSUE TITLE
Membres fondateurs, dispositions transitoires

### ISSUE THREAD

**Issue by pandark** [pandark/asn-statuts#19]
> ## Membres fondateurs, dispositions transitoires ##
> 
> Les cinq membres fondateurs sont chargés de désigner les dirigeants de l'association pour le premier exercice, jusqu'à la tenue de la première assemblée générale.
> Fait à Paris le 5 avril 2017, établi en 6 exemplaires originaux par les membres fondateurs.

**Comment by pandark** [comment]
Nombre de membres fondateurs et d'exemplaires, ainsi que la date à changer.

**Comment by d-bourdon** [comment]
ne pas oublier : nb exemplaire = nb membre +1 (toujours pratique de le noter)
