### ISSUE TITLE
Anciens membres actifs : maintien de certains services ? statut particulier ?

### ISSUE THREAD

**Issue by pandark** [pandark/asn-statuts#22]
Il peut être intéressant de maintenir certains services aux anciens membres actifs de l'association (redirection mail, par exemple), voire de leur donner un statut particulier.
Dans un réseau d'anciens, on peut trouver des gens pour faire des confs, des partenariats, des recommandations pour les membres…

Il y a déjà

> Les services peuvent, dans le cadre d’accords ou de contrats autorisés par le Bureau, être fournis à des personnes physiques ou morales n’étant pas membres de l’Association.

qui permet de le faire, mais ce n'est pas très spécifique et ce n'est pas dans cette optique que la phrase a été écrite.

**Comment by d-bourdon** [comment]
Pas faux, un student qui fini 42 et qui était membre, ça peut être reloux de perdre une redirection. mais du coup faut qu'il participe encore ou pas (cotisation, etc .. )

edit: ou oui effectivement faire un statut différent de membre distribuer a la discrétion du bureau pour ceux qui ont participer a l'assos et qui partent (style membre d'honneur) enfin si j'ai comprit ce que tu voulais dire

**Comment by pandark** [comment]
> Les anciens membres actifs qui le demandent peuvent, si le Bureau l'autorise, bénéficier de certains services, comme une redirection mail.

Quelques explication parce qu'on en a parlé face à face en fait 🙂 : Avoir des membres d'honneur, ça veut dire faire deux types de membres et spécifier ce qui s'applique ou non à ce type de membre (vote, services, etc.) et ça semble un peu définitif…
Et le but n'est pas que ça soit automatique pour que ça concerne les anciens membres qui se sentent encore suffisamment proches de l'association pour en faire la demande (et se sont suffisamment impliqués pour qu'elle soit acceptée).
