### ISSUE TITLE
Matériel

### ISSUE THREAD

**Issue by pandark** [pandark/asn-statuts#24]
Si on veut pouvoir prêter du matériel aux membres, il faut peut-être en parler dans les statuts.

**Comment by pandark** [comment]
Préciser aussi que les projets construits avec du matériel acheté par l'association sont la propriété de l'association, et pourront être rachetés (à prix coutant ou plus) aux membres ayant participé ou à d'autres personnes si ceux-ci ne sont pas intéressés.

**Comment by d-bourdon** [comment]
Quand tu découvre une new issue xD ouaip et préciser qu'en cas de casse/dommage, l'utilisateur doit rembourser et aussi que sur certain objet, une caution peut être demandé qui.sera rendu a la fin du prêt

**Comment by pandark** [comment]
https://github.com/asn42/statuts/pull/33/commits/9880f4a9005f52f8beb66fbe09cd6071964dcd1a#diff-af76d581c7e0d4da42a9645a9e0e802cR164
