### ISSUE TITLE
[article] Admission des membres

### ISSUE THREAD

**Issue by pandark** [pandark/asn-statuts#5]
Un article sur les membres de l'association et leur adhésion à celle-ci.

> ## Admission des membres ##
> 
> L’Association se compose des membres adhérents personnes physiques. Sont membres adhérents, les personnes qui ont adhéré à l’association, ont réglé leur cotisation, fixée annuellement par le Bureau et qui participent à la réalisation de l’objet de l’Association.
> 
> Pour devenir membre de l'Association, il faut :
> - avoir été agréé préalablement, par le Bureau,
> - régler sa cotisation,
> - et s’engager à respecter les statuts et le Règlement Intérieur, s’il y a lieu, de l’Association.
> 
> Toute demande d’agrément d’un nouveau membre devra être adressée au Bureau de l’Association, accompagnée d’un exposé écrit (sous forme physique ou informatique) des motifs de la demande d’adhésion du postulant.
> Le Bureau statue sur la demande d’adhésion et décide d’agréer ou non le postulant.
> Le refus d’admission n’a pas à être motivé.
> L’accession et le maintien de la qualité de membre est soumis au paiement d’une cotisation annuelle dont le montant est fixé annuellement par le Bureau et au respect des statuts et du règlement intérieur de l’Association, s’il existe.
> 
> Chaque membre devra régler sa cotisation annuelle au plus tard le 31 janvier de chaque année.
> Les cotisations seront réglées :
> - par chèque libellé au nom de l’Association adressé au siège de l’Association, à l’attention du Trésorier,
> - ou par virement bancaire sur le compte bancaire de l’Association,
> - ou en espèces, contre remise d’un justificatif du Trésorier de l’Association,
> - ou par carte bancaire, si l’Association a mis en place un tel mode de règlement.
> 
> Le Bureau peut proposer une réduction ou une exemption de cotisation pour des membres dont les faibles moyens financiers présenteraient un obstacle à l'adhésion, sur présentation d'un justificatif. Pour bénéficier de ces conditions préférentielles, l’adhérent doit en faire la demande en présentant les justificatifs nécessaires auprès du Bureau, qui a toute latitude pour statuer.
> Sauf quand les conditions donnant droit au tarif préférentiel sont par nature définitives, l’adhérent devra présenter un justificatif régulièrement pour pouvoir continuer à bénéficier de ces conditions préférentielles.
> 
> La participation aux activités de l’Association à des personnes, qui n’en sont pas membres, est possible, sur décision du Bureau.

**Comment by pandark** [comment]
<del>Cotisation fixée par le Bureau ou par une Assemblée Générale ?</del>
<del>Exemption de cotisation possible sur décision du Bureau à sa discrétion après présentation de justificatifs ?</del>
Déplacer la dernière partie dans l'article Activités et services (?)

**Comment by d-bourdon** [comment]
Aménagement, voire exemption possible de cotisation pour les membres qui le demandent et en justifient le besoin, à l'appréciation du Bureau.

**Comment by pandark** [comment]
> Le Bureau peut proposer une réduction ou une exemption de cotisation pour des membres dont les faibles moyens financiers présenteraient un obstacle à l'adhésion, sur présentation d'un justificatif. Pour bénéficier de ces conditions préférentielles, l’adhérent doit en faire la demande en présentant les justificatifs nécessaires auprès du Bureau, qui a toute latitude pour statuer.
> Sauf quand les conditions donnant droit au tarif préférentiel sont par nature définitives, l’adhérent devra présenter un justificatif régulièrement pour pouvoir continuer à bénéficier de ces conditions préférentielles.

Fait.
