### ISSUE TITLE
[article] Radiation

### ISSUE THREAD

**Issue by pandark** [pandark/asn-statuts#6]
Un article sur la perte de la qualité de membre.

> ## Radiation ##
> 
> La qualité de membre de l’Association se perd par :
> 
> 1. la démission, notifiée par un membre par courrier simple ou courrier électronique, au Président de l’Association, la perte de la qualité de membre intervenant alors à compter de la réception du courrier ;
> 2. l’exclusion prononcée par le Bureau pour défaut de paiement de la cotisation annuelle du membre ;
> 3. l’exclusion prononcée par le Bureau pour motif grave ou comportement contraire à l’intérêt de l’Association ; l’adhérent intéressé est préalablement convoqué devant le Bureau pour fournir ses explications ;
> 4. l’exclusion prononcée par le Bureau, en cas de perte de la qualification ou du statut de l’adhérent ayant motivé l’agrément par le Bureau; l’adhérent intéressé est préalablement convoqué devant le Bureau pour fournir ses explications ;
> 5. le placement sous sauvegarde de justice ou mise en tutelle ou curatelle d’un membre.
> 
> Aucun remboursement des cotisations, ne sera effectué en cas de perte de la qualité de membre pour quelque titre que ce soit.
> Sont considérés comme des motifs graves pouvant entraîner l’exclusion d’un membre :
> 
> - toute initiative directe ou indirecte d’un membre visant à diffamer l’Association ou
certains de ses membres ou à porter atteinte aux objectifs poursuivis par l’Association ;
> - le non respect des statuts, du règlement intérieur de l'Association ou de la lois française ;
> - l'atteinte volontaire aux services de l'association ;
> - de manière plus générale pour tout motif jugé grave par un nombre suffisant de membres du Bureau ou une Assemblée Générale.

**Comment by pandark** [comment]
Faute grave :
- <del>Ajouter l'atteinte volontaire aux services de l'association et tout acte illégale ou contraire aux statuts ou à la lois.</del>
- <del>Ajouter une phrase ouverte « de manière plus générale pour tout motif jugé grave par un nombre suffisant de membres du Bureau ou une Assemblée Générale. »</del>

Fait.

**Comment by d-bourdon** [comment]
Fin de cotisation ? limite a 1an pour la cotisation (membre un an) ou modifier `La qualité de membre de l’Association se perd par :` en `Un membre de l’Association peut être radier pour les motifs de :` ?
